### ISSUE TITLE
unexpected value 

### ISSUE THREAD

**Issue by neo-xy** [Jaspero/ng2-select#12]
when running ng build --prod I'm getting error:

> Unexpected value 'JasperoSelectModule in ../node_modules/@jaspero/ng2-select/dist/index.d.ts' imported by the module 'AppModule in ../src/app/app.module.ts'. Please add
a @NgModule annotation.

that goes as well for "alerts"
anyone have any idea how to fix that?
  (found some posts that it accures whit the latest version of angular but no solution:S)

**Comment by flauc** [comment]
This has been fixed, sorry for the delay.
