### ISSUE TITLE
how to get selected value from this component?

### ISSUE THREAD

**Issue by xiehongyang** [Jaspero/ng2-select#5]
read your code but can't find any @Output() attribute.
so I wonder how could i can get selected value? Thx~

**Comment by flauc** [comment]
Hi @xiehongyang. We use a form value accessor, so you will need to use ReactiveForms to get the value. Basically you stick a `formControlName` on the element.

**Comment by xiehongyang** [comment]
Ok Thanks for your answer! so fast! Thx

**Comment by flauc** [comment]
Happy to help, let me know if you need any help setting it up.

**Comment by xiehongyang** [comment]
sorry - - I am too dull to using formControlName 
I just write a code like this: 
```
this.envForm = new FormGroup({
       env: new FormControl()
    })
```
and this is html:
```
 <jaspero-select formControlName="env"></jaspero-select>
```
and met a problem: 
**ERROR Error: 
      ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
      formGroup's partner directive "formControlName" instead.**
Could u write some component's side code demo? : )

**Comment by xiehongyang** [comment]
Sorry : (  I guess I misunderstand what u mean - - I am so dull 
Could u write some demo code for me, just some simple code both html side and component side?
So much thanks!= =

**Comment by flauc** [comment]
Yes no problem, here you go: 

template: 
```html
<form [formGroup]="form">
  <jaspero-select  formControlName="test" [options]="options"></jaspero-select>
</form>
```

component: 
```ts

  constructor(private _fb: FormBuilder) {}

  options: any[] = [
        {name: 12},
        {name: 24},
        {name: 48}
    ];

  form: FormGroup;

  ngOnInit() {
    this.form = this._fb.group({test: ''});
  }
```

In order for this to work, you will need to have `ReactiveForms` imported in your `AppModule`.

**Comment by flauc** [comment]
I should really include a minimal example in the documentation. We will add that today.

**Comment by xiehongyang** [comment]
Thx~~! Actually I am writing like this, So that must be some problem in other place ：） I am a Chinese.Forgive my  Poor English- -But really appreciate what u have done for me! Thank u!

**Comment by xiehongyang** [comment]
After Check all the code around, I still met this error : 
```
ProjectRedisAssignment.html:143 ERROR TypeError: this.selected.forEach is not a function
    at SelectComponent.webpackJsonp.../../../../@jaspero/ng2-select/dist/src/select.component.js.SelectComponent.writeValue (select.component.js:144)
    at setUpControl (forms.es5.js:1743)
    at FormGroupDirective.webpackJsonp.../../../forms/@angular/forms.es5.js.FormGroupDirective.addControl (forms.es5.js:4711)
    at FormControlName.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControlName._setUpControl (forms.es5.js:5299)
    at FormControlName.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControlName.ngOnChanges (forms.es5.js:5217)
    at checkAndUpdateDirectiveInline (core.es5.js:10812)
    at checkAndUpdateNodeInline (core.es5.js:12238)
    at checkAndUpdateNode (core.es5.js:12177)
    at debugCheckAndUpdateNode (core.es5.js:12880)
    at debugCheckDirectivesFn (core.es5.js:12821)
    at Object.View_ProjectRedisAssignment_4.co [as updateDirectives] (ProjectRedisAssignment.html:143)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12806)
    at checkAndUpdateView (core.es5.js:12144)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.es5.js:12746)
```

my html：
```
<jaspero-select [hidden]="envModel === 'online'"
                              [options]="envModelOfflineArray"
                              [key]="'name'"
                              [multi]="true"
                              formControlName="env"
              ></jaspero-select>
```
my component: 
```
envForm: FormGroup;

  envFormInit() {
    this.envForm = this.fb.group({
      'env': ''
    })
  }
```
Could u give me some hint : ) ?

**Comment by flauc** [comment]
Hmm, I'm not entirely sure, but will do some research. For now, can you try changing the component to this:
```
  envFormInit() {
    this.envForm = this.fb.group({
      'env': {name: 'something'}
    })
  }
```
Set the name to a value from your options arrray.

**Comment by xiehongyang** [comment]
template:

```
<form [formGroup]="form">
  <jaspero-select  formControlName="test" [options]="options"></jaspero-select>
</form>
```
component:

 ```
 constructor(private _fb: FormBuilder) {}

  options: any[] = [
        {name: 12},
        {name: 24},
        {name: 48}
    ];

  form: FormGroup;

  ngOnInit() {
    this.form = this._fb.group({test: ''});
  }
```
Sorry, It seems if I change the **options** Array later, the options in your component still doesn't update

**Comment by neo-xy** [comment]
@flauc I think You would need to change 
`if(value!==undefined) `
to
`if(value)`
in order to make it work with form controller

**Comment by xiehongyang** [comment]
@neo-xy thank you very much! I will try it!
